use markdown editor
kaiyuanshe/OSS-toolbox pull request #14
Opened 2024-06-30 15:53 UTC by luojiyin1987

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #12

2024-07-07 07:49 UTC, luojiyin1987 commented
报错 
```ReferenceError: document is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
Object.<anonymous>
file:///home/luo/nodeWork/OSS-toolbox/node_modules/.pnpm/edkit@1.2.1_typescript@5.4.5/node_modules/edkit/dist/index.js (1:4386)```

应该是我没处理好 
```javascript
private Core = createRef<HTMLEditor>();
```
要怎样处理 `Core` 的值的传递？  @TechQuery

2024-07-07 08:23 UTC, TechQuery requested changes

2024-07-07 08:23 UTC, TechQuery commented on components/Git/ArticleEditor.tsx
> +          <HTMLEditor defaultValue={''} onChange={this.Core.current} />
为什么要把一个组件实例传给一个回调函数？

2024-07-07 08:23 UTC, TechQuery commented on components/Git/ArticleEditor.tsx
>      return this.Core.current;
不需要改，这块都没有用了，要删掉。

2024-07-07 08:23 UTC, TechQuery commented on components/Git/ArticleEditor.tsx
> +import HTMLEditor from '../Form/HTMLEditor';
[你遇到的问题][1]就是因为这里静态导入就会在服务端渲染的时候也打包进去，后端自然找不到富文本编辑器所需要的前端 `document` 对象。

所以我们需要动态导入：https://github.com/kaiyuanshe/OpenHackathon-Web/blob/4a80163f1d3ee8e11cac5083a0c62e0f78580465/components/Activity/ActivityEditor.tsx#L17

[1]: https://github.com/kaiyuanshe/OSS-toolbox/pull/14#issuecomment-2212358550

2024-07-07 08:45 UTC, luojiyin1987 commented on components/Git/ArticleEditor.tsx
>      return this.Core.current;
那 getContent  函数怎么运行？

2024-07-07 12:46 UTC, TechQuery commented on components/Git/ArticleEditor.tsx
>      return this.Core.current;
> 那 getContent  函数怎么运行？ 

内部的取值通过其它可观察属性来实现

2024-07-09 09:53 UTC, luojiyin1987 commented
不知道怎样处理 core 的值。  @TechQuery

2024-07-09 10:23 UTC, TechQuery commented
> 不知道怎样处理 core 的值。  @TechQuery 

不同的组件传参方式不同，新组件已经和 `this.core` 没关系了。

不要被现有代码影响，你就搞清楚“新组件的值从哪来，又到哪去”就行了。

2024-07-10 15:16 UTC, luojiyin1987 commented
fixURL   里面的逻辑怎么处理？  

` core.root.querySelectorAll('img[src], audio[src], video[src]'),`   意义是什么？ 
@TechQuery

2024-07-10 20:50 UTC, TechQuery requested changes

2024-07-10 20:50 UTC, TechQuery commented on components/Git/ArticleEditor.tsx
> +    if (this.editorContent) this.editorContent = content;
```suggestion
    this.editorContent = content;
```
以前需要判空是因为 `this.core` 是用来存组件实例对象的，只有存在才能存取它的属性。

而现在你是直接存取编辑器里的数据，就直接存取就好了。

2024-07-10 20:50 UTC, TechQuery commented on components/Git/ArticleEditor.tsx
> +          <HTMLEditor defaultValue={this.editorContent} />
```suggestion
          <HTMLEditor
            defaultValue={this.editorContent}
            onChange={value => (this.editorContent = value)}
          />
```

2024-07-10 20:50 UTC, TechQuery commented on components/Git/ArticleEditor.tsx
> +  accessor editorContent = '';
```suggestion

  editorContent = '';
```
没有什么特殊需要用普通属性就好了，不需要存取器属性。

2024-07-10 21:03 UTC, TechQuery commented
> fixURL   里面的逻辑怎么处理？  
> 
> ` core.root.querySelectorAll('img[src], audio[src], video[src]'),`   意义是什么？

它们就是在把编辑框里的路径处理成本网页真正能加载的 URL。

在新编辑器里：

```JS
const root = document.querySelector('div[contenteditable]');
```

2024-07-11 10:57 UTC, TechQuery commented on components/Git/ArticleEditor.tsx
> +    if (this.editorContent) this.editorContent = content;
还有不止一处同类代码

2024-07-11 14:17 UTC, TechQuery requested changes

2024-07-11 14:17 UTC, TechQuery commented on components/Git/ArticleEditor.tsx
> +    this.editorContent = '';
直接调用 `this.reset()`

2024-07-11 17:08 UTC, TechQuery requested changes

2024-07-11 17:08 UTC, TechQuery commented on components/Git/ArticleEditor.tsx
> +    this.reset();
可简化为：

```js
 if (!value.trim()) this.reset();
```

2024-07-11 17:08 UTC, TechQuery commented on components/Git/ArticleEditor.tsx
>              </Button>
新编辑器已含该功能，此按钮及其引用的数据、方法皆可删除。

2024-07-11 17:08 UTC, TechQuery commented on translation/en-US.ts
> +  filePath: 'filePath',
```suggestion
  file_path: 'filePath',
```
翻译的键名采用下划线连接风格。

2024-07-11 17:08 UTC, TechQuery commented on translation/en-US.ts
> +  // git pager
```suggestion
  // Git Pager
```

2024-07-12 09:40 UTC, TechQuery requested changes

2024-07-12 09:40 UTC, TechQuery commented on translation/en-US.ts
> +  commit_message: 'commit Message',
```suggestion
  file_path: 'file path',
  commit_message: 'commit message',
```

2024-07-12 12:04 UTC, TechQuery approved these changes

2024-07-12 12:05 UTC, merged