change  SCP GitHub action
kaiyuanshe/OSS-toolbox pull request #16
Opened 2024-07-13 16:59 UTC by luojiyin1987

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #XXXXX

2024-07-13 17:07 UTC, TechQuery requested changes

2024-07-13 17:07 UTC, TechQuery commented on .github/workflows/deploy-production.yml
> +            echo '${{ secrets.SSH_KEY }}' | sudo -S ./start.sh /tmp/${{ env.BOX_NAME }}/build/${{ env.ARTIFACT_PATH }}
没必要多加一层 `build` 目录吧？

2024-07-13 18:03 UTC, TechQuery requested changes

2024-07-13 18:03 UTC, TechQuery commented on .github/workflows/deploy-production.yml
> -            mkdir -p ~/${{ env.BOX_NAME }}
此处不需要变更吧？

2024-07-13 18:13 UTC, luojiyin1987 commented on .github/workflows/deploy-production.yml
> +            echo '${{ secrets.SSH_KEY }}' | sudo -S ./start.sh /tmp/${{ env.BOX_NAME }}/build/${{ env.ARTIFACT_PATH }}
```shell
source: ./build/*.*
strip_components: 1
``` 
两个配合使用

2024-07-13 18:14 UTC, luojiyin1987 commented on .github/workflows/deploy-production.yml
> -            mkdir -p ~/${{ env.BOX_NAME }}
我习惯先创建

2024-07-13 18:57 UTC, TechQuery commented on .github/workflows/deploy-production.yml
> -            mkdir -p ~/${{ env.BOX_NAME }}
> 我习惯先创建

倒没有什么大问题，只是一般 PR 会遵循最小变更原则。

2024-07-13 18:57 UTC, TechQuery approved these changes

2024-07-13 18:59 UTC, merged

2024-07-14 00:10 UTC, luojiyin1987 commented on .github/workflows/deploy-production.yml
> -            mkdir -p ~/${{ env.BOX_NAME }}
```shell
cd /tmp/${{ env.BOX_NAME }}
mv docker-compose.yml start.sh ~/${{ env.BOX_NAME }}
```
在一起， 好理解当前所在目录