build: slim-docker-github-action
kaiyuanshe/OSS-toolbox pull request #20
Opened 2024-07-24 12:39 UTC by luojiyin1987

[![PR-20](https://badgen.net/badge/GitHub.dev/PR-20/blue?icon=visualstudio)](https://github.dev/kaiyuanshe/OSS-toolbox/pull/20) [![PR-20](https://badgen.net/badge/GitHub%20codespaces/PR-20/black?icon=github)](https://codespaces.new/kaiyuanshe/OSS-toolbox/pull/20) [![PR-20](https://badgen.net/badge/GitPod.io/PR-20/orange?icon=git)](https://gitpod.io/?autostart=true#https://github.com/kaiyuanshe/OSS-toolbox/pull/20) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=kaiyuanshe&utm_campaign=badge_info)

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #XXXXX

2024-07-24 13:43 UTC, luojiyin1987 commented
https://github.com/kitabisa/docker-slim-action/issues/7   解决  slim docker  找不到 docker 镜像的问题

2024-07-24 13:57 UTC, luojiyin1987 commented
https://github.com/appleboy/scp-action/issues/160    解决 scp-action   can't open 'build/artifact.tar': Permission  的报错

2024-07-24 14:32 UTC, luojiyin1987 commented
https://github.com/slimtoolkit/slim/issues/211     还等人修

2024-07-24 16:00 UTC, luojiyin1987 commented
![image](https://github.com/user-attachments/assets/fd1b5daa-4767-44ed-afc2-bc8a79f1cccd)
https://github.com/marketplace/actions/docker-slim-github-action 
要向上游提 pr 才行。

2024-07-28 06:01 UTC, TechQuery requested changes

2024-07-28 06:01 UTC, TechQuery commented on .github/workflows/deploy-production.yml
> +            ${{ env.BOX_URL }}:latest
```suggestion
          tags: ${{ env.BOX_URL }}:latest
          load: true
```
遵循最小变更原则

2024-07-28 06:01 UTC, TechQuery commented on .github/workflows/deploy-production.yml
> +          docker images
```suggestion
      - name: show Docker image
        run: docker images
```

2024-07-28 06:01 UTC, TechQuery commented on .github/workflows/deploy-production.yml
> +      - name: Slim Docker image
```suggestion
      - name: Slim Docker image
```
注释没必要写和步骤名一样的文字。

2024-07-28 06:01 UTC, TechQuery commented on Dockerfile
> +CMD ["npm","start"]
此处无需变更。

2024-07-28 06:01 UTC, TechQuery commented on start.sh
> -docker image prune -a -f
此处不要删，因为重新导入同名镜像之后，之前的镜像就没有用了。

2024-07-28 09:13 UTC, luojiyin1987 commented on start.sh
> -docker image prune -a -f
如果别的服务的容器停止运行，会把镜像删除的。

2024-07-28 09:38 UTC, TechQuery commented on start.sh
> -docker image prune -a -f
> 如果别的服务的容器停止运行，会把镜像删除的。

没关系，停服的再跑一遍 action 打新镜像就行了。

2024-08-02 15:45 UTC, luojiyin1987 commented
放弃使用 distroless 镜像，该镜像没 curl wget，bash，sh，连 apt 一类Linux包管理软件也没 ，只有对应语言的运行环境。攻击面极少，安全性高， 但很难进行调试。 以后优先考虑使用  standalone , nextjs 自己从 node_modules 抽取出来。

不建议使用 slim 相关，逻辑处理非常粗暴，根本补不完。

2024-08-02 18:44 UTC, TechQuery requested changes

2024-08-02 18:44 UTC, TechQuery commented on Dockerfile
> +FROM  base
无需变更

2024-08-02 18:44 UTC, TechQuery commented on .github/workflows/deploy-production.yml
> +          chmod 664 ${{ env.ARTIFACT_PATH }}
不用 slim action 了，这些可以还原了吧？

2024-08-02 18:59 UTC, TechQuery commented
@luojiyin1987 改完 review 后给上游脚手架提个 PR：https://github.com/idea2app/Next-Bootstrap-ts

2024-08-03 00:12 UTC, luojiyin1987 commented on Dockerfile
> +FROM  base
还是要复制 node_modules 文件夹？

2024-08-03 06:21 UTC, TechQuery commented on Dockerfile
> +FROM  base
> 还是要复制 node_modules 文件夹？  那镜像大小到 800M duo 了。

你仔细看，我指的是第 19 行无需多余空格。

2024-08-03 10:39 UTC, luojiyin1987 commented on Dockerfile
> +CMD ["npm","start"]
镜像里是有 nodejs， 但没 npm 了

2024-08-03 13:46 UTC, TechQuery requested changes

2024-08-03 13:46 UTC, TechQuery commented on Dockerfile
> +ENV PORT 3000
```suggestion
ENV PORT=3000
```

2024-08-03 13:47 UTC, TechQuery approved these changes

2024-08-03 13:49 UTC, merged

2024-08-04 12:28 UTC, luojiyin1987 commented
https://github.com/vercel/next.js/pull/68486
给上游提个 PR， 消除 GitHub action 的[警告](https://github.com/kaiyuanshe/OSS-toolbox/actions/runs/10227259451/job/28298523029)
![image](https://github.com/user-attachments/assets/f27dc3bd-dcd1-46e1-bee2-6b5304d7697d)