[fix] handle noMore
kaiyuanshe/OSS-toolbox pull request #9
Opened 2024-05-31 05:42 UTC by hu-qi

Checklist（清单）:

- [ ] Labels 
- [ ] Assignees
- [ ] Reviewers

Closes #8

2024-06-06 04:03 UTC, TechQuery requested changes

2024-06-06 04:03 UTC, TechQuery commented on models/Repository.ts
> +    }
`noMore` 是一个计算值，关键要找出已加载数据总长度 `this.allItems.length`和 `this.totalCount` 之间为什么算不出 `this.noMore === true`。

2024-06-06 05:19 UTC, hu-qi commented on models/Repository.ts
> +    }
> `noMore` 是一个计算值，关键要找出已加载数据总长度 `this.allItems.length`和 `this.totalCount` 之间为什么算不出 `this.noMore === true`。

刚看到这块代码您已经重构了,是不是得修改上游库了?

2024-06-06 05:59 UTC, hu-qi commented on models/Repository.ts
> +    }
看到 renderList 这拿到的 totalCount 是 Infinity

2024-06-06 12:53 UTC, TechQuery commented on models/Repository.ts
> +    }
> 刚看到这块代码您已经重构了,是不是得修改上游库了?

是的

2024-06-06 12:55 UTC, TechQuery commented on models/Repository.ts
> +    }
>  看到 renderList 这拿到的 totalCount 是 Infinity

不应该呀，我从另一个接口已经取到了所有仓库的总数返回回去了。

2024-06-07 00:55 UTC, hu-qi commented on models/Repository.ts
> +    }
> > 看到 renderList 这拿到的 totalCount 是 Infinity
> 
> 不应该呀，我从另一个接口已经取到了所有仓库的总数返回回去了。

代码之谜: 我在 mbox-github 加多一行 `console.log(pageData, totalCount )` 就能拿到对的 totalCount 

![image](https://github.com/kaiyuanshe/OSS-toolbox/assets/17986122/5c711f49-392a-48a9-ad60-dc0c7b0b3027)

2024-06-07 00:57 UTC, hu-qi commented on models/Repository.ts
> +    }
> > 看到 renderList 这拿到的 totalCount 是 Infinity
> 
> 不应该呀，我从另一个接口已经取到了所有仓库的总数返回回去了。

注释掉 console 拿到的就是 Infinity
![image](https://github.com/kaiyuanshe/OSS-toolbox/assets/17986122/f5b07d64-031b-4f03-b0d2-4e15df112fe0)

2024-06-09 06:09 UTC, hu-qi commented
已尝试修改, 您看看这么改行不行@TechQuery  
中途我的变基操作可能不对,导致 pr 被 close 了.

2024-06-09 10:06 UTC, TechQuery approved these changes

2024-06-09 10:09 UTC, merged